name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Install Windows SDK 10.0.16299
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/p/?linkid=864422 -OutFile winsdk.exe
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo
        $startInfo.FileName = "winsdk.exe"
        $startInfo.Arguments = "/norestart /quiet"
        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $startInfo
        $process.Start()
        $process.WaitForExit()
    
    - name: Install .NET 5
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 5.0.x

    - name: Install .NET 6
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Add MSBuild to PATH
      uses: glennawatson/setup-msbuild@v1.0.3
      with:
        prerelease: true
        
    - name: Install DotNet workloads
      shell: bash
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install tvos
        dotnet workload install macos
        dotnet workload install maui
    
    - uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild /t:build,pack /nowarn:MSB4011 /maxcpucount /p:NoPackageAnalysis=true /verbosity:minimal /p:Configuration=release RxProperty.sln
      working-directory: source

    - name: NuGet Push
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} **/*.nupkg
        
